# -*- coding: utf-8 -*-
"""test deepsort

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m1_ucDfMUnAOwyu4H9O7x4vtBIvLfN3R
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive
!git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Yolov5_DeepSort_Pytorch
!pip install -r requirements.txt

import torch
##torch.cuda.is_available()
from IPython.display import Image, clear_output

clear_output()
print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Yolov5_DeepSort_Pytorch

!python3 track.py --yolo_model /content/drive/MyDrive/Yolov5_DeepSort_Pytorch/best.pt --source /content/drive/MyDrive/Yolov5_DeepSort_Pytorch/Live_Walking.mp4  --save-vid  # show live inference results as well